// <auto-generated />
namespace THi_PIIT_DANGVANTIEN.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BitCoinDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BitCoinDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202204020209217_ BitCoinDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
